import 'dart:async';
import 'dart:math';

import 'package:deliveryfood/models/models.dart';
import 'package:deliveryfood/shared/shared.dart';
import 'package:deliveryfood/ui/widgets/widgets.dart';
import 'package:flutter/material.dart';
import 'package:flutter/rendering.dart';
import 'package:flutter_spinkit/flutter_spinkit.dart';
import 'package:google_fonts/google_fonts.dart';
import 'package:intl/intl.dart';
import 'package:supercharged/supercharged.dart';
import 'package:get/get.dart';
import 'package:dropdown_plus/dropdown_plus.dart';

part 'general_page.dart';
part 'sign_in_page.dart';
part 'sign_up_page.dart';
part 'adrres_page.dart';
part 'main_page.dart';
part 'food_page.dart';
part 'food_detail_page.dart';
part 'payment_page.dart';
part 'ilustration_page.dart';
part 'success_sign_up.dart';
part 'success_order_page.dart';
part 'order_history_page.dart';
part 'profile_page.dart';
part 'splash_screen.dart';
